package editor

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// SeedSQL reads tmp/ CSVs + map.json and writes INSERT statements to outFile.
func SeedSQL(tmpDir, mapFile, outFile string) error {
	cfg, err := LoadMapConfig(mapFile)
	if err != nil {
		return err
	}

	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("create output file: %w", err)
	}
	defer f.Close()

	fmt.Fprintln(f, "-- Generated by tbledit seed")
	fmt.Fprintln(f, "-- Run: tbledit seed -o herorebirth_seed.sql")
	fmt.Fprintln(f, "SET NAMES utf8mb4;")
	fmt.Fprintln(f, "SET foreign_key_checks = 0;")
	fmt.Fprintln(f)

	rowsTotal := 0
	for fname, tblCfg := range cfg {
		csvName := strings.TrimSuffix(fname, ".tbl") + ".csv"
		csvPath := filepath.Join(tmpDir, csvName)

		rows, _, err := readCSV(csvPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "SKIP %s: %v\n", fname, err)
			continue
		}

		fmt.Fprintf(f, "-- Source: %s\n", fname)

		for _, tgt := range tblCfg.Targets {
			n, err := writeInserts(f, tgt, rows)
			if err != nil {
				fmt.Fprintf(os.Stderr, "ERROR %s -> %s: %v\n", fname, tgt.Table, err)
				continue
			}
			rowsTotal += n
		}
		fmt.Fprintln(f)
	}

	fmt.Fprintln(f, "SET foreign_key_checks = 1;")
	fmt.Printf("Wrote %d rows → %s\n", rowsTotal, outFile)
	return nil
}

// writeInserts generates INSERT ... ON DUPLICATE KEY UPDATE statements for one target.
func writeInserts(f *os.File, tgt TableTarget, allRows [][]string) (int, error) {
	// Determine SQL field names (unique, ordered, excluding array/coord helpers)
	type fieldInfo struct {
		name string
		role string
	}

	// Pass 1: discover all unique SQL fields in output order
	var fields []fieldInfo
	fieldSeen := map[string]bool{}

	// For array fields, record which col indices contribute to each field
	type arrayEntry struct {
		colIdx     int
		filterZero bool
	}
	arrayFields := map[string][]arrayEntry{}   // field -> []colIdx
	matKeyFields := map[string][]int{}         // field -> []colIdx (keys)
	matValFields := map[string][]int{}         // field -> []colIdx (values)
	coordXField := map[string]int{}            // field -> colIdx
	coordYField := map[string]int{}            // field -> colIdx

	for i, cm := range tgt.Cols {
		if cm.Field == "" {
			continue
		}
		switch cm.Role {
		case "array":
			arrayFields[cm.Field] = append(arrayFields[cm.Field], arrayEntry{i, cm.FilterZero})
			if !fieldSeen[cm.Field] {
				fields = append(fields, fieldInfo{cm.Field, "array"})
				fieldSeen[cm.Field] = true
			}
		case "mat_key":
			matKeyFields[cm.Field] = append(matKeyFields[cm.Field], i)
			if !fieldSeen[cm.Field] {
				fields = append(fields, fieldInfo{cm.Field, "mat"})
				fieldSeen[cm.Field] = true
			}
		case "mat_val":
			matValFields[cm.Field] = append(matValFields[cm.Field], i)
		case "coord_x":
			coordXField[cm.Field] = i
			if !fieldSeen[cm.Field] {
				fields = append(fields, fieldInfo{cm.Field, "coord"})
				fieldSeen[cm.Field] = true
			}
		case "coord_y":
			coordYField[cm.Field] = i
		default:
			if !fieldSeen[cm.Field] {
				fields = append(fields, fieldInfo{cm.Field, cm.Role})
				fieldSeen[cm.Field] = true
			}
		}
	}

	if len(fields) == 0 {
		return 0, nil
	}

	// Build direct col index map (for simple fields)
	directCol := map[string]int{}
	directRole := map[string]string{}
	for i, cm := range tgt.Cols {
		if cm.Field == "" {
			continue
		}
		switch cm.Role {
		case "array", "mat_key", "mat_val", "coord_x", "coord_y":
			// handled via special maps
		default:
			// last write wins (e.g. duplicate tradable cols)
			directCol[cm.Field] = i
			directRole[cm.Field] = cm.Role
		}
	}

	colNames := make([]string, len(fields))
	for i, fi := range fields {
		colNames[i] = "`" + fi.name + "`"
	}

	updateClauses := make([]string, len(fields))
	for i, fi := range fields {
		updateClauses[i] = fmt.Sprintf("`%s`=VALUES(`%s`)", fi.name, fi.name)
	}

	written := 0
	startRow := 1 + tgt.SkipCol // row 0 = header

	fmt.Fprintf(f, "INSERT INTO `%s` (%s) VALUES\n",
		tgt.Table, strings.Join(colNames, ","))

	var valueLines []string

	for r := startRow; r < len(allRows); r++ {
		row := allRows[r]
		vals := make([]string, len(fields))

		for fi, finfo := range fields {
			switch finfo.role {
			case "array":
				entries := arrayFields[finfo.name]
				var parts []string
				for _, e := range entries {
					if e.colIdx >= len(row) {
						continue
					}
					v := row[e.colIdx]
					if e.filterZero && (v == "0" || v == "0.0" || v == "") {
						continue
					}
					parts = append(parts, v)
				}
				vals[fi] = sqlStr(strings.Join(parts, ","))

			case "mat":
				keys := matKeyFields[finfo.name]
				valCols := matValFields[finfo.name]
				obj := make(map[string]interface{})
				for j, keyIdx := range keys {
					if keyIdx >= len(row) {
						continue
					}
					k := row[keyIdx]
					if k == "0" || k == "" {
						continue
					}
					var v interface{} = "0"
					if j < len(valCols) && valCols[j] < len(row) {
						v = row[valCols[j]]
					}
					obj[k] = v
				}
				b, _ := json.Marshal(obj)
				vals[fi] = sqlStr(string(b))

			case "coord":
				xIdx, hasX := coordXField[finfo.name]
				yIdx, hasY := coordYField[finfo.name]
				x, y := "0", "0"
				if hasX && xIdx < len(row) {
					x = row[xIdx]
				}
				if hasY && yIdx < len(row) {
					y = row[yIdx]
				}
				vals[fi] = sqlStr(fmt.Sprintf("(%s,%s)", x, y))

			default:
				colIdx, ok := directCol[finfo.name]
				role := directRole[finfo.name]
				if !ok || colIdx >= len(row) {
					vals[fi] = "NULL"
					continue
				}
				v := row[colIdx]
				switch role {
				case "bool":
					vals[fi] = boolVal(v)
				case "json_text":
					escaped, _ := json.Marshal(map[string]string{"text": v})
					vals[fi] = sqlStr(string(escaped))
				default:
					vals[fi] = numOrStr(v)
				}
			}
		}

		valueLines = append(valueLines, "("+strings.Join(vals, ",")+")")
		written++
	}

	if len(valueLines) == 0 {
		fmt.Fprintln(f, "-- (no rows)")
		return 0, nil
	}

	fmt.Fprintln(f, strings.Join(valueLines, ",\n"))
	fmt.Fprintf(f, "ON DUPLICATE KEY UPDATE %s;\n\n", strings.Join(updateClauses, ","))

	return written, nil
}

// sqlStr escapes a string value for SQL.
func sqlStr(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	return "'" + s + "'"
}

// boolVal converts "0"/"1"/etc. to TRUE/FALSE.
func boolVal(v string) string {
	if v == "0" || v == "" || strings.ToLower(v) == "false" {
		return "FALSE"
	}
	return "TRUE"
}

// numOrStr decides whether to quote the value.
// Integers, floats → unquoted. Anything else → quoted.
func numOrStr(v string) string {
	if v == "" || strings.ToLower(v) == "null" {
		return "NULL"
	}
	if _, err := strconv.ParseInt(v, 10, 64); err == nil {
		return v
	}
	if _, err := strconv.ParseFloat(v, 64); err == nil {
		return v
	}
	return sqlStr(v)
}
